services:
  postgres:
    image: postgres:11-alpine
    container_name: event_db
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d  # Pasta de migrações
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eventdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: