server:
  port: 8081
  servlet:
    context-path: /api

app:
  jwt:
    secret: YDXmzA0pfWGr5GxizbA7NdGQrusADUvZm9dDw8jzqpo= # usar comando "openssl rand -base64 32" para gerar token
    expirationMs: 86400000 # 24 horas em milissegundos

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/eventdb
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: postgres
    password: admin@123
    url: jdbc:postgresql://localhost:5433/eventdb
  profiles:
    active: dev
  mail:
    host: localhost
    port: 25
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json

  # Configurações de Email
  #mail:
  #  host: smtp.gmail.com
  #  port: 587
  #  username: desafio-pitang@gmail.com
  #  password: teste
  #  properties:
  #    mail:
  #      smtp:
  #        auth: true
  #        starttls:
  #          enable: true