server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

app:
  jwt:
    secret: i5qeaxblbQ6lPJqtD36HKNZXc4Gu0SKv9dIBnj7DQ6/jgur4Nedg3HQizzqC7dcwDvNAMqFcqzQ+WHULOngTow==
    expirationMs: 864000000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/eventdb
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: postgres
    password: admin@123
    url: jdbc:postgresql://localhost:5433/eventdb
  profiles:
    active: dev
  mail:
    host: localhost
    port: 25
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: TRACE
        data: INFO
        boot: INFO
      hibernate: INFO
