server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

app:
  jwt:
    secret: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.5Xnwnka59mxsFFvvUSa0Q_V9Oi7tc3oCk5TJeYzNPCYiC8UxKXnRdFYn7f4kY1CNdqTrVYbSNvqqP1kq6WPDDQ
    expirationMs: 864000000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/eventdb
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: postgres
    password: admin@123
    url: jdbc:postgresql://localhost:5433/eventdb
  profiles:
    active: dev
  mail:
    host: localhost
    port: 25
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json

  # Configurações de Email
  #mail:
  #  host: smtp.gmail.com
  #  port: 587
  #  username: desafio-pitang@gmail.com
  #  password: teste
  #  properties:
  #    mail:
  #      smtp:
  #        auth: true
  #        starttls:
  #          enable: true

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: TRACE
        data: INFO
        boot: INFO
      hibernate: INFO
  file:
    name: logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"