spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/eventdb
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: postgres
    password: admin@123
    url: jdbc:postgresql://localhost:5433/eventdb
  profiles:
    active: dev
  mail:
    host: localhost
    port: 25

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100

  # Configurações de Email
  #mail:
  #  host: smtp.gmail.com
  #  port: 587
  #  username: desafio-pitang@gmail.com
  #  password: teste
  #  properties:
  #    mail:
  #      smtp:
  #        auth: true
  #        starttls:
  #          enable: true